{% set name = "enum_tools" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/enum_tools-{{ version }}.tar.gz
  sha256: 13ceb9376a4c5f574a1e7c5f9c8eb7f3d3fbfbb361cc18a738df1a58dfefd460

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.6
    - whey >=0.0.20
  run:
    - pygments >=2.6.1
    - python >=3.6
    - typing-extensions >=3.7.4.3
  run_constrained:
    - sphinx >=3.4.0
    - sphinx-toolbox >=2.16.0

test:
  imports:
    - enum_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/domdfcoding/enum_tools
  summary: Tools to expand Python's enum module.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://enum_tools.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
