{% set name = "enum_tools" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/enum_tools-{{ version }}.tar.gz
  sha256: 0d13335e361d300dc0f8fd82c8cf9951417246f9676144f5ee1761eb690228eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - whey >=0.0.20
  run:
    - pygments >=2.6.1
    - python >={{ python_min }}
    - typing-extensions >=3.7.4.3
  run_constrained:
    - sphinx >=3.4.0
    - sphinx-toolbox >=2.16.0

test:
  imports:
    - enum_tools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/domdfcoding/enum_tools
  summary: Tools to expand Python's enum module.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://enum_tools.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - jan-janssen
    - domdfcoding
